### PR TITLE
fix(tlb): write back original vttbr

### PR DESCRIPTION
**Pull request by xioliu**

### CODE REVIEW

**Comment by xioliu** [comment]
Hum, I am not sure why it failed at code quality. @DavidMCerdeira

**Comment by DavidMCerdeira** [comment]
@xioliu We had an issue with the clang-format tool. It should be fixed now. However you need to rebase with main to apply the fix.

**Comment by xioliu** [comment]
Well, I got "Already up to date." when I run git pull.

**Comment by DavidMCerdeira** [comment]
@xioliu Your branch is one commit behind bao-project/bao-hypervisor:main
 You are most likely pulling from your own main

**Pull request closed without merging**
