### PR TITLE
fix(core/interrupts): fix intp reserve condition

### PR DESCRIPTION
**Pull request by D3boker1**
This commit fixes the interrupts_reserve function. The current condition allows the hypervisor to reserve an interrupt by only checking if it is in the correct range. By introducing the interrupt_is_reserved() function and incorporating it into the conditional statement, we avoid reassigning an interrupt ID that has already been reserved.

### CODE REVIEW

**Comment by josecm** [comment]
Thanks, s this check should have been there already! I think we could take this a step forward. Add another function that checks if the interrupt is in  `global_interrupt_bitmap`  because the interrupt might be reserved for a guest also. Maybe renaming the `interrupt_is_reserved` function is in order to something like `interrupt_assigned_to_hyp` :thinking:

**Comment by josecm** [comment]
@D3boker1 could you address this? If you don't have any idle cycles to spare, I'd be happy to do it.

**Review by DavidMCerdeira — CHANGES_REQUESTED** [review]
It's better to name `interrupt_globally_assigned` as `interrupt_assigned`. Interrupts are not assigned globally, they are marked as assigned in a global bitmap.

Otherwise looks good.

**Comment by D3boker1** [comment]
Hi @DavidMCerdeira
Please find the suggested change in commit 73730d0ee2f921369fd4f7e16fe1d2ba282ee965

**Review by josecm — APPROVED** [review]

**Review by DavidMCerdeira — CHANGES_REQUESTED** [review]
Looks good.
Please clean the git history to avoid having the commit with the function name change.

Either squash de commits, or keep the two other commits with the correct name from the start

**Review by DavidMCerdeira — APPROVED** [review]

**Pull request merged**
