### PR TITLE
New improved printk implementation

### PR DESCRIPTION
**Pull request by josecm**
The quality of the previous printk implementation was less than desirable. This PR introduces a new improved, and more robust printk implementation that allows to print strings larger than the allocated print buffers and also adds the "format printf" attribute so that incorrect type identifiers in the format string are detected at compile-time.

### CODE REVIEW

**Review by DavidMCerdeira — APPROVED** [review]

**Comment by DavidMCerdeira** [comment]
@josecm at least one CI check is failing

**Review by danielRep — APPROVED** [review]

**Comment by josecm** [comment]
@DavidMCerdeira 

> @josecm at least one CI check is failing

The error was due to an "undefined reference to `__aeabi_uldivmod" error in 32-bit arm architectures since we don't link the GCC lib. I don't fully understand why this intrinsic was being invoked for one of the divisions but not for the others. Anyway, I believe I fixed this by removing the use of `long long` since the print functions don't support these types in the first place.

**Review by danielRep — APPROVED** [review]
I have tested `console_printk` locally with some unit tests and it seems to been working properly.

**Comment by josecm** [comment]
> I have tested `console_printk` locally with some unit tests and it seems to been working properly.

Thanks!

**Review by ninolomata — APPROVED** [review]

**Review by AfonsoSantos96 — APPROVED** [review]

**Pull request merged**
